### ISSUE TITLE
6 high vulnerabilities in version 1.0.1

### ISSUE THREAD

**Issue by MastalerzKamil** [horizon-ui/horizon-ui-chakra-pro-ts#1]
Hello,
I have noticed that version 1.0.1 has 6 high vulnerabilities. Please fix them. 

Reproduction steps:
1. unzip files
2. run `npm install`

Then you should see 
<img width="1722" alt="image" src="https://user-images.githubusercontent.com/15552565/191737061-efb0a6af-b11f-4fd2-b37a-0fd79e1977b9.png">

**Comment by simmmpleweb** [comment]
The problem with errors is due to react-scripts. To fix the problem you might want to use Vite or Next.js, for which we have a different version.
